name: Deploy addon release
on:
  push:
    tags:
    - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Package
      uses: QartemisT/packager@master
      if: ${{ github.event_name != 'pull_request' }}
      with:
        args: -g bcc -n "Gehennas-Blacklist-Data-{project-version}{classic}"
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
