name: unban-command
on:
  repository_dispatch:
    types: [unban-command]
jobs:
  unban:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pull request
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
    - name: Install Lua
      uses: leafo/gh-actions-lua@v9
    - name: Unban
      run: |
        lua unban.lua ${{ github.event.client_payload.slash_command.args.named.list }} ${{ github.event.client_payload.slash_command.args.unnamed.all }}
    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"
    - name: Commit ban
      run: |
        git config --global user.name "Gehennas-EU Bot"
        git config --global user.email 110223061+Gehennas-EU-Bot@users.noreply.github.com
        git remote add base https://x-access-token:${{ secrets.BOT_ACCESS_TOKEN }}@github.com/Gehennas-EU/blacklist.git
        git commit -a -m "remove ${{ github.event.client_payload.slash_command.args.unnamed.all }} in ${{ github.event.client_payload.slash_command.args.named.list }}; closes #${{ github.event.client_payload.github.payload.issue.number }}"
        git push
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          No longer Blacklisted ${{ github.event.client_payload.slash_command.args.unnamed.all }}!

          ![KEKWait](https://cdn.betterttv.net/emote/619928e554f3344f88068ac1/2x)
